---
version: 2
plan:
  project-key: MARS
  key: ROCKET
  name: Build the Rocket
stages:
  - Build hull:
    - React-JS-CI

React-JS-CI:
  tasks:
   - script:
       interpreter: SHELL
       scripts:
         - rm -rf bamboo-specs/
       description: Removing yaml file from the reactjs.
   - any-task:
       plugin-key: com.atlassian.bamboo.plugins.bamboo-nodejs-plugin:task.builder.npm
       configuration:
         isolatedCache: 'false'
         runtime: Node.js Path 14-03-2022
         command: install
       description: Node.JS install (It will create node_modules folder)	 
   - any-task:
       plugin-key: com.atlassian.bamboo.plugins.bamboo-nodejs-plugin:task.builder.npm
       configuration:
        isolatedCache: 'false'
        runtime: Node.js
        command: run build
       description: Node.JS run build (It will create build folder)
